s = input()
n = len(s)
white = sum(1 for c in s if c in '_')
lower = sum(1 for c in s if c in 'abcdefghijklmnopqrstuvwxyz')
upper = sum(1 for c in s if c in 'ABCDEFGHIJKLMNOPQRSTUVWXYZ')
symbols = sum(1 for c in s if c not in '_abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ')
print(white / n)
print(lower / n)
print(upper / n)
print(symbols / n)
